"use client";

import { cn } from "@contextjule/ui/lib/utils";
import { useMemo } from "react";
import type * as React from "react";

import { juleEngine } from "../jule/render";
import { Sprite } from "./sprite";

/**
 * The outdoor scene: a fixed three-stop sky over a two-tone grass field, with a
 * stepped pixel cloud and a tuft row. This is the one place in the whole system
 * a gradient is allowed, and only two surfaces get it — the home screen and the
 * panel — which is what makes it read as *the* place she lives.
 *
 * The clouds and tufts are generated by the same engine that draws her, so the
 * scene cannot drift out of the palette.
 *
 * Positions default to the home screen's numbers from
 * `designs/screens/app-screens.html`, measured — like the sheet itself — from
 * the frame's top-left source pixel. See `Sprite`'s `anchor` prop.
 */
export interface SceneProps extends React.ComponentProps<"div"> {
  scale?: number;
  action?: string;
  state?: string;
  /** Sky gradient stops, as percentages. Home is 52/74, the panel is 54/78. */
  skyStops?: readonly [number, number];
  grassHeight?: number;
  /** The darker strip at the very front of the field. */
  grassShadeHeight?: number;
  showCloud?: boolean;
  showTufts?: boolean;
  cloud?: { right: number; top: number; scale?: number };
  tufts?: { left: number; bottom: number; scale?: number };
  /** `left`/`bottom` of her frame's origin pixel, or `center` to centre her. */
  character?: { left: number | "center"; bottom: number };
}

function Scene({
  scale = 4,
  action = "idle",
  state,
  skyStops = [52, 74],
  grassHeight = 96,
  grassShadeHeight = 30,
  showCloud = true,
  showTufts = true,
  cloud = { right: 34, top: 30, scale: 4 },
  tufts = { left: 0, bottom: 74, scale: 4 },
  character = { left: 248, bottom: 188 },
  className,
  children,
  style,
  ...props
}: SceneProps) {
  const cloudGrid = useMemo(() => {
    const j = juleEngine();
    const g = j.mk(14, 6);
    j.r(g, 4, 0, 8, 0, "u");
    j.r(g, 2, 1, 11, 2, "u");
    j.r(g, 0, 3, 13, 4, "u");
    j.r(g, 2, 5, 11, 5, "q");
    return g;
  }, []);

  const tuftGrid = useMemo(() => {
    const j = juleEngine();
    const g = j.mk(110, 8);
    for (let i = 0; i < 16; i++) {
      const x = 3 + i * 7 + (i % 3);
      const h = 3 + (i % 3);
      j.r(g, x, 8 - h, x, 7, "V");
      j.r(g, x - 1, 9 - h, x + 1, 7, "G");
    }
    return g;
  }, []);

  const centred = character.left === "center";

  return (
    <div
      data-slot="scene"
      className={cn("relative overflow-hidden", className)}
      style={{
        background: `linear-gradient(var(--scene-sky-top) 0%, var(--scene-sky-mid) ${skyStops[0]}%, var(--scene-sky-low) ${skyStops[1]}%)`,
        ...style,
      }}
      {...props}
    >
      {showCloud ? (
        <Sprite
          grid={cloudGrid}
          scale={cloud.scale ?? 4}
          anchor="origin"
          className="absolute opacity-90"
          style={{ right: cloud.right, top: cloud.top }}
        />
      ) : null}

      {/* Grass: a lit lip over the field, and a darker strip at the very front. */}
      <div
        className="absolute inset-x-0 bottom-0 border-t-[5px]"
        style={{
          height: grassHeight,
          background: "var(--scene-grass)",
          borderTopColor: "var(--scene-grass-lip)",
        }}
      />
      <div
        className="absolute inset-x-0 bottom-0"
        style={{ height: grassShadeHeight, background: "var(--scene-grass-shade)" }}
      />

      {showTufts ? (
        <Sprite
          grid={tuftGrid}
          scale={tufts.scale ?? 4}
          anchor="origin"
          className="absolute"
          style={{ left: tufts.left, bottom: tufts.bottom }}
        />
      ) : null}

      {/* Her feet sit on the last painted row, so she is anchored from the bottom. */}
      <Sprite
        action={action}
        state={state}
        scale={scale}
        fx={false}
        anchor={centred ? "box" : "origin"}
        className={cn("absolute z-[2]", centred && "left-1/2 -translate-x-1/2")}
        style={centred ? { bottom: character.bottom } : { left: character.left, bottom: character.bottom }}
      />

      {children}
    </div>
  );
}

export { Scene };
