"use client";

import { patrolAt, patrolDuration } from "@contextjule/core/patrol";
import { Sprite } from "@contextjule/ui/components/sprite";
import { juleEngine, renderStrip, type RenderedFrame } from "@contextjule/ui/jule/render";
import { useEffect, useMemo, useState } from "react";

/**
 * The hero band. Her stage, not a picture of her.
 *
 * Everything in it — the clouds, the tufts, her — is generated by the same
 * sprite engine that draws the app, so the band cannot drift out of the
 * palette. The hill is a clip-path rather than a sprite because it spans the
 * full width at any viewport, and a 2000px grid would be absurd.
 *
 * The loop is driven by an interval reading the wall clock, not by
 * requestAnimationFrame alone: rAF is throttled to nothing in a background tab
 * and would strand her mid-step. `patrolAt` is a pure function of elapsed time,
 * so a sparse tick still lands on the right pose.
 *
 * Vertical positions come in two sets. The design sheet is drawn at a 700px
 * band and assumes a 1100px minimum width; the smaller set is the same
 * composition at phone height. They are CSS custom properties rather than props
 * so a media query can switch them — an inline `style` cannot.
 */

/** Tuned to the sheet: about 22 seconds end to end. */
const PATROL = { walkMs: 9_000, settleMs: 600, waveMs: 1_300 } as const;

/** Her travel, as a percentage of the band. Matches the sheet's 6% → 58%. */
const TRAVEL = { from: 6, to: 58 } as const;

const SCALE = { small: 4, large: 5 } as const;

export function HeroStage({ children }: { children?: React.ReactNode }) {
  return (
    <header
      className={[
        "relative isolate overflow-hidden",
        // The band, and every offset measured from its floor.
        "h-[560px] [--grass:150px] [--grass-lip:146px] [--grass-front:48px] [--grass-tufts-a:118px] [--grass-tufts-b:46px] [--hill:144px] [--hill-h:56px] [--jule-bottom:186px]",
        "sm:h-[620px] sm:[--grass:176px] sm:[--grass-lip:172px] sm:[--grass-front:56px] sm:[--grass-tufts-a:136px] sm:[--grass-tufts-b:54px] sm:[--hill:170px] sm:[--hill-h:68px] sm:[--jule-bottom:214px]",
        "lg:h-[700px] lg:[--grass:204px] lg:[--grass-lip:198px] lg:[--grass-front:64px] lg:[--grass-tufts-a:158px] lg:[--grass-tufts-b:62px] lg:[--hill:196px] lg:[--hill-h:78px] lg:[--jule-bottom:246px]",
      ].join(" ")}
      style={{ background: "linear-gradient(#2f7fb8 0%, #4fb3e8 48%, #93d8f2 68%)" }}
    >
      <Clouds />

      {/* The hill silhouette behind the field. */}
      <div
        aria-hidden
        className="absolute inset-x-0"
        style={{
          bottom: "var(--hill)",
          height: "var(--hill-h)",
          background: "#3f7d44",
          clipPath:
            "polygon(0 100%,0 66%,6% 66%,6% 40%,13% 40%,13% 72%,25% 72%,25% 28%,33% 28%,33% 58%,45% 58%,45% 36%,54% 36%,54% 68%,65% 68%,65% 32%,73% 32%,73% 60%,85% 60%,85% 42%,93% 42%,93% 70%,100% 70%,100% 100%)",
        }}
      />

      {/* The field: body, lit lip, and a darker strip at the very front. */}
      <div
        aria-hidden
        className="absolute inset-x-0 bottom-0 bg-[#5aa84f]"
        style={{ height: "var(--grass)" }}
      />
      <div
        aria-hidden
        className="absolute inset-x-0 h-[6px] bg-[#6dbd5e]"
        style={{ bottom: "var(--grass-lip)" }}
      />
      <div
        aria-hidden
        className="absolute inset-x-0 bottom-0 bg-[#4f9846]"
        style={{ height: "var(--grass-front)" }}
      />
      <div
        aria-hidden
        className="absolute inset-x-0 h-[6px]"
        style={{
          bottom: "calc(var(--grass-front) - 2px)",
          background: "repeating-linear-gradient(90deg,#4f9846 0 12px,transparent 12px 40px)",
        }}
      />

      <TuftRow seed={0} scale={5} bottomVar="--grass-tufts-a" />
      <TuftRow seed={3} scale={6} bottomVar="--grass-tufts-b" className="opacity-90" />

      <Walker />

      {/* The copy layer. Pointer events only on the interactive parts, so she
          passes behind the text freely. */}
      <div className="pointer-events-none absolute inset-x-0 top-0 z-[3] flex flex-col px-5 pt-9 sm:pt-12 md:px-10 lg:pt-14">
        <div className="pointer-events-auto flex max-w-[580px] flex-col gap-5">{children}</div>
      </div>
    </header>
  );
}

/** Three stepped pixel clouds, baked once. */
function Clouds() {
  const clouds = useMemo(() => {
    const j = juleEngine();
    const cloud = (width: number) => {
      const grid = j.mk(width, 7);
      const q = (n: number) => Math.max(0, Math.round(width * n));
      j.r(grid, q(0.24), 0, q(0.42), 0, "u");
      j.r(grid, q(0.58), 0, q(0.74), 0, "u");
      j.r(grid, q(0.14), 1, q(0.86), 1, "u");
      j.r(grid, q(0.07), 2, width - 2, 3, "u");
      j.r(grid, 0, 4, width - 1, 5, "u");
      j.r(grid, q(0.1), 6, width - 3, 6, "q");
      return grid;
    };
    return { a: cloud(22), b: cloud(16), c: cloud(12) };
  }, []);

  return (
    <>
      <Sprite
        grid={clouds.a}
        scale={5}
        anchor="origin"
        className="absolute top-[120px] left-[58%] lg:top-[214px] lg:left-[64%]"
      />
      <Sprite
        grid={clouds.b}
        scale={4}
        anchor="origin"
        className="absolute top-[74px] right-[7%] opacity-85 lg:top-[132px] lg:right-[9%]"
      />
      <Sprite
        grid={clouds.c}
        scale={4}
        anchor="origin"
        className="absolute top-[34px] left-[42%] opacity-70 lg:top-[52px] lg:left-[46%]"
      />
    </>
  );
}

/** A row of grass tufts, drawn by the engine so it stays in palette. */
function TuftRow({
  seed,
  scale,
  bottomVar,
  className,
}: {
  seed: number;
  scale: number;
  bottomVar: string;
  className?: string;
}) {
  const grid = useMemo(() => {
    const j = juleEngine();
    const row = j.mk(200, 10);
    for (let i = 0; i < 26; i++) {
      const x = 3 + i * 8 + ((i * 7 + seed) % 5);
      const height = 4 + ((i * 3 + seed) % 4);
      j.r(row, x, 10 - height, x, 9, "V");
      j.r(row, x - 1, 12 - height, x + 1, 9, "G");
      j.d(row, x, 10 - height, "V");
    }
    return row;
  }, [seed]);

  return (
    <Sprite
      grid={grid}
      scale={scale}
      anchor="origin"
      className={`absolute left-0 ${className ?? ""}`}
      style={{ bottom: `var(${bottomVar})` }}
    />
  );
}

/**
 * Her, walking the band.
 *
 * Every frame of every action is rendered once into a `box-shadow` string and
 * then swapped by index. Regenerating a 30x40 grid ten times a second would
 * burn a phone's battery for no visible gain.
 */
function Walker() {
  const [scale, setScale] = useState<number>(SCALE.small);
  const [elapsed, setElapsed] = useState(0);

  useEffect(() => {
    const query = window.matchMedia("(min-width: 1024px)");
    const apply = () => setScale(query.matches ? SCALE.large : SCALE.small);
    apply();
    query.addEventListener("change", apply);
    return () => query.removeEventListener("change", apply);
  }, []);

  const strips = useMemo(
    () => ({
      walk: renderStrip("walk", scale, { fx: false }),
      walkBack: renderStrip("walk", scale, { fx: false }, true),
      wave: renderStrip("wave", scale, { fx: false }),
      idle: renderStrip("idle", scale, { fx: false }),
    }),
    [scale],
  );

  useEffect(() => {
    const reduced = window.matchMedia("(prefers-reduced-motion: reduce)");
    if (reduced.matches) return;

    const startedAt = Date.now();
    const total = patrolDuration(PATROL);
    // 24fps is the sheet's rate. An interval rather than rAF alone, so a
    // background tab does not strand her mid-step.
    const id = setInterval(() => setElapsed((Date.now() - startedAt) % total), 1000 / 24);
    return () => clearInterval(id);
  }, []);

  const patrol = patrolAt(elapsed, PATROL);
  const strip: RenderedFrame[] =
    patrol.action === "walk"
      ? patrol.mirrored
        ? strips.walkBack
        : strips.walk
      : patrol.action === "wave"
        ? strips.wave
        : strips.idle;

  const fps = patrol.action === "wave" ? 12 : patrol.action === "walk" ? 10 : 8;
  const frame = strip[Math.floor((elapsed / 1000) * fps) % strip.length] ?? strip[0];
  const left = TRAVEL.from + (TRAVEL.to - TRAVEL.from) * patrol.position;

  if (!frame) return null;

  return (
    <Sprite
      frame={frame}
      anchor="origin"
      className="absolute z-[2]"
      style={{ left: `${left.toFixed(2)}%`, bottom: "var(--jule-bottom)" }}
    />
  );
}
