/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as MiniBarRouteImport } from './routes/mini-bar'
import { Route as OverlayRouteImport } from './routes/overlay'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as SpeechRouteImport } from './routes/speech'
import { Route as TrayRouteImport } from './routes/tray'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppGrowthRouteImport } from './routes/_app/growth'
import { Route as AppNudgesRouteImport } from './routes/_app/nudges'
import { Route as AppSessionsRouteImport } from './routes/_app/sessions'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const MiniBarRoute = MiniBarRouteImport.update({
  id: '/mini-bar',
  path: '/mini-bar',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlayRoute = OverlayRouteImport.update({
  id: '/overlay',
  path: '/overlay',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeechRoute = SpeechRouteImport.update({
  id: '/speech',
  path: '/speech',
  getParentRoute: () => rootRouteImport,
} as any)
const TrayRoute = TrayRouteImport.update({
  id: '/tray',
  path: '/tray',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppGrowthRoute = AppGrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => AppRoute,
} as any)
const AppNudgesRoute = AppNudgesRouteImport.update({
  id: '/nudges',
  path: '/nudges',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsRoute = AppSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/mini-bar': typeof MiniBarRoute
  '/overlay': typeof OverlayRoute
  '/panel': typeof PanelRoute
  '/speech': typeof SpeechRoute
  '/tray': typeof TrayRoute
  '/growth': typeof AppGrowthRoute
  '/nudges': typeof AppNudgesRoute
  '/sessions': typeof AppSessionsRoute
}
export interface FileRoutesByTo {
  '/mini-bar': typeof MiniBarRoute
  '/overlay': typeof OverlayRoute
  '/panel': typeof PanelRoute
  '/speech': typeof SpeechRoute
  '/tray': typeof TrayRoute
  '/growth': typeof AppGrowthRoute
  '/nudges': typeof AppNudgesRoute
  '/sessions': typeof AppSessionsRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/mini-bar': typeof MiniBarRoute
  '/overlay': typeof OverlayRoute
  '/panel': typeof PanelRoute
  '/speech': typeof SpeechRoute
  '/tray': typeof TrayRoute
  '/_app/growth': typeof AppGrowthRoute
  '/_app/nudges': typeof AppNudgesRoute
  '/_app/sessions': typeof AppSessionsRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mini-bar'
    | '/overlay'
    | '/panel'
    | '/speech'
    | '/tray'
    | '/growth'
    | '/nudges'
    | '/sessions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/mini-bar'
    | '/overlay'
    | '/panel'
    | '/speech'
    | '/tray'
    | '/growth'
    | '/nudges'
    | '/sessions'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/mini-bar'
    | '/overlay'
    | '/panel'
    | '/speech'
    | '/tray'
    | '/_app/growth'
    | '/_app/nudges'
    | '/_app/sessions'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  MiniBarRoute: typeof MiniBarRoute
  OverlayRoute: typeof OverlayRoute
  PanelRoute: typeof PanelRoute
  SpeechRoute: typeof SpeechRoute
  TrayRoute: typeof TrayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mini-bar': {
      id: '/mini-bar'
      path: '/mini-bar'
      fullPath: '/mini-bar'
      preLoaderRoute: typeof MiniBarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlay': {
      id: '/overlay'
      path: '/overlay'
      fullPath: '/overlay'
      preLoaderRoute: typeof OverlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speech': {
      id: '/speech'
      path: '/speech'
      fullPath: '/speech'
      preLoaderRoute: typeof SpeechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tray': {
      id: '/tray'
      path: '/tray'
      fullPath: '/tray'
      preLoaderRoute: typeof TrayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/growth': {
      id: '/_app/growth'
      path: '/growth'
      fullPath: '/growth'
      preLoaderRoute: typeof AppGrowthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nudges': {
      id: '/_app/nudges'
      path: '/nudges'
      fullPath: '/nudges'
      preLoaderRoute: typeof AppNudgesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions': {
      id: '/_app/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AppSessionsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppGrowthRoute: typeof AppGrowthRoute
  AppNudgesRoute: typeof AppNudgesRoute
  AppSessionsRoute: typeof AppSessionsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppGrowthRoute: AppGrowthRoute,
  AppNudgesRoute: AppNudgesRoute,
  AppSessionsRoute: AppSessionsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  MiniBarRoute: MiniBarRoute,
  OverlayRoute: OverlayRoute,
  PanelRoute: PanelRoute,
  SpeechRoute: SpeechRoute,
  TrayRoute: TrayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
